### PR TITLE
add image renderer plugin so we can share images in slack

### PR DESCRIPTION
**Pull request by matschaffer**

### CODE REVIEW

**Comment by matschaffer** [comment]
I put this on https://grafana.safecast.cc as a test, but doesn't work yet. Guess we need some other OS package still.

```
t=2020-06-05T00:27:26+0000 lvl=eror msg="Render request failed" logger=plugins.backend pluginId=grafana-image-renderer url="http://localhost:3001/d-solo/DFSxrOLWk/safecast-device-details?orgId=1&from=1591230442460&to=1591316842460&var-device_urn=geigiecast:62313&panelId=14&width=1000&height=500&tz=Asia%2FTokyo&render=1" error="Error: Failed to launch chrome!\n/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome: error while loading shared libraries: libXcursor.so.1: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n"
t=2020-06-05T00:27:26+0000 lvl=eror msg="Rendering failed." logger=context userId=2 orgId=1 uname=matschaffer error="Rendering failed: Error: Failed to launch chrome!\n/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome: error while loading shared libraries: libXcursor.so.1: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n"
t=2020-06-05T00:27:26+0000 lvl=eror msg="Request Completed" logger=context userId=2 orgId=1 uname=matschaffer method=GET path=/render/d-solo/DFSxrOLWk/safecast-device-details status=500 remote_addr="122.223.153.21, 172.31.27.55" time_ms=18 size=1723 referer="https://grafana.safecast.cc/d/DFSxrOLWk/safecast-device-details?orgId=1&from=now-24h&to=now&var-device_urn=geigiecast:62313"
(END)
```

**Comment by matschaffer** [comment]
Screen Shot 2020-06-05 at 9 27 28 AM

**Comment by matschaffer** [comment]
trying `yum install libXcomposite libXdamage libXtst cups libXScrnSaver pango atk adwaita-cursor-theme adwaita-icon-theme at at-spi2-atk at-spi2-core cairo-gobject colord-libs dconf desktop-file-utils ed emacs-filesystem gdk-pixbuf2 glib-networking gnutls gsettings-desktop-schemas gtk-update-icon-cache gtk3 hicolor-icon-theme jasper-libs json-glib libappindicator-gtk3 libdbusmenu libdbusmenu-gtk3 libepoxy liberation-fonts liberation-narrow-fonts liberation-sans-fonts liberation-serif-fonts libgusb libindicator-gtk3 libmodman libproxy libsoup libwayland-cursor libwayland-egl libxkbcommon m4 mailx nettle patch psmisc redhat-lsb-core redhat-lsb-submod-security rest spax time trousers xdg-utils xkeyboard-config` per https://grafana.com/docs/grafana/latest/administration/image_rendering/#troubleshooting

**Comment by matschaffer** [comment]
Still same error looks like

**Comment by matschaffer** [comment]
Dropping this since the docker setup in #10 has it fixed

**Comment by shehrozkhan88** [comment]
#9

**Pull request closed without merging**
